name: Let_Us_Know
description: "uts cuy"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.9.2  # Pastikan ini ada di dev_dependencies
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - img/book.png
    - img/mathematics.png
    - img/science.png
    - img/musical.png